/**
 * Push the Lark notification workflow to all GitHub org repos.
 *
 * This script creates or updates .github/workflows/lark-notify.yml in each
 * repository so that GitHub events trigger Lark notifications automatically.
 */

import { Octokit } from '@octokit/rest';
import { loadConfig } from './config.js';

const WORKFLOW_PATH = '.github/workflows/lark-notify.yml';

/** The notification workflow content that gets pushed to each repo. */
function workflowContent(syncRepoFullName: string): string {
  return `# Auto-generated by feishu-github-sync — do not edit manually.
# This workflow sends GitHub event notifications to the linked Lark group chat.
# Source: https://github.com/${syncRepoFullName}

name: Lark Notifications

on:
  push:
    branches: [main, master]
  issues:
    types: [opened, closed, reopened, assigned, labeled]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, reopened, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted]
  release:
    types: [published]
  create:
  delete:
  fork:
  workflow_run:
    workflows: ["*"]
    types: [completed]

permissions:
  contents: read

jobs:
  notify-lark:
    runs-on: ubuntu-latest
    # Only run for non-bot events to avoid loops
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout feishu-github-sync
        uses: actions/checkout@v4
        with:
          repository: ${syncRepoFullName}
          token: \${{ secrets.SYNC_GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Send Lark notification
        env:
          LARK_APP_ID: \${{ secrets.LARK_APP_ID }}
          LARK_APP_SECRET: \${{ secrets.LARK_APP_SECRET }}
          LARK_DOMAIN: \${{ vars.LARK_DOMAIN || 'feishu' }}
          LARK_CHAT_ID: \${{ vars.LARK_CHAT_ID }}
          GITHUB_EVENT_NAME: \${{ github.event_name }}
          GITHUB_EVENT_PATH: \${{ github.event_path }}
        run: npx tsx src/notify.ts
`;
}

async function main() {
  const config = loadConfig();
  const octokit = new Octokit({ auth: config.githubToken });
  const syncRepoFullName = process.env.GITHUB_REPOSITORY ?? `${config.githubOrg}/feishu-github-sync`;

  console.log(`=== Setup: Push notification workflow to ${config.githubOrg} repos ===\n`);

  // List all org repos
  const repos: Array<{ name: string; full_name: string; default_branch: string }> = [];
  for await (const response of octokit.paginate.iterator(octokit.repos.listForOrg, {
    org: config.githubOrg,
    per_page: 100,
    type: 'all',
  })) {
    for (const repo of response.data) {
      // Skip the sync repo itself
      if (repo.full_name === syncRepoFullName) continue;
      repos.push({
        name: repo.name,
        full_name: repo.full_name,
        default_branch: repo.default_branch ?? 'main',
      });
    }
  }

  console.log(`Found ${repos.length} repos (excluding sync repo)\n`);

  const content = workflowContent(syncRepoFullName);
  const contentBase64 = Buffer.from(content).toString('base64');

  let created = 0;
  let updated = 0;
  let skipped = 0;
  let errors = 0;

  for (const repo of repos) {
    try {
      // Check if file already exists
      let existingSha: string | undefined;
      try {
        const existing = await octokit.repos.getContent({
          owner: config.githubOrg,
          repo: repo.name,
          path: WORKFLOW_PATH,
        });
        if ('sha' in existing.data) {
          existingSha = existing.data.sha;
          // Check if content is the same
          if ('content' in existing.data) {
            const existingContent = Buffer.from(
              (existing.data.content as string).replace(/\n/g, ''),
              'base64',
            ).toString();
            if (existingContent === content) {
              console.log(`  ~ ${repo.full_name} — already up to date`);
              skipped++;
              continue;
            }
          }
        }
      } catch {
        // File doesn't exist — that's fine
      }

      if (config.dryRun) {
        console.log(`  [DRY RUN] ${repo.full_name} — would ${existingSha ? 'update' : 'create'}`);
        existingSha ? updated++ : created++;
        continue;
      }

      await octokit.repos.createOrUpdateFileContents({
        owner: config.githubOrg,
        repo: repo.name,
        path: WORKFLOW_PATH,
        message: existingSha
          ? 'chore: update Lark notification workflow'
          : 'chore: add Lark notification workflow',
        content: contentBase64,
        sha: existingSha,
        branch: repo.default_branch,
      });

      if (existingSha) {
        console.log(`  ✓ ${repo.full_name} — updated`);
        updated++;
      } else {
        console.log(`  + ${repo.full_name} — created`);
        created++;
      }
    } catch (err) {
      console.error(`  ✗ ${repo.full_name} — failed: ${err}`);
      errors++;
    }
  }

  console.log('\n=== Summary ===');
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Skipped: ${skipped} (already up to date)`);
  console.log(`Errors:  ${errors}`);

  if (errors > 0) process.exit(1);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
